config/routes.rb
Rails.application.routes.draw do
  resources :articls
  root "articles#index"
  
 get "articles", to: "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/articl.rb
class Articl < ApplicationRecord
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all 
  end
end

app/controllers/articls_controller.rb
class ArticlsController < ApplicationController
  before_action :set_articl, only: %i[ show edit update destroy ]

  # GET /articls or /articls.json
  def index
    @articls = Articl.all
  end

  # GET /articls/1 or /articls/1.json
  def show
  end

  # GET /articls/new
  def new
    @articl = Articl.new
  end

  # GET /articls/1/edit
  def edit
  end

  # POST /articls or /articls.json
  def create
    @articl = Articl.new(articl_params)

    respond_to do |format|
      if @articl.save
        format.html { redirect_to articl_url(@articl), notice: "Articl was successfully created." }
        format.json { render :show, status: :created, location: @articl }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @articl.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articls/1 or /articls/1.json
  def update
    respond_to do |format|
      if @articl.update(articl_params)
        format.html { redirect_to articl_url(@articl), notice: "Articl was successfully updated." }
        format.json { render :show, status: :ok, location: @articl }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @articl.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articls/1 or /articls/1.json
  def destroy
    @articl.destroy

    respond_to do |format|
      format.html { redirect_to articls_url, notice: "Articl was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_articl
      @articl = Articl.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def articl_params
      params.require(:articl).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/articls_helper.rb
module ArticlsHelper
end

app/views/articles/index.html.erb
<h1>Articles</h1>
<ul>
   <% @articles.each do |article|%>
   <li>
   <%= article.title %>
   </li>
<% end %>
</ul>

app/views/articls/_articl.html.erb
<div id="<%= dom_id articl %>">
  <p>
    <strong>Title:</strong>
    <%= articl.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= articl.description %>
  </p>

</div>

app/views/articls/_form.html.erb
<%= form_with(model: articl) do |form| %>
  <% if articl.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(articl.errors.count, "error") %> prohibited this articl from being saved:</h2>

      <ul>
        <% articl.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articls/edit.html.erb
<h1>Editing articl</h1>

<%= render "form", articl: @articl %>

<br>

<div>
  <%= link_to "Show this articl", @articl %> |
  <%= link_to "Back to articls", articls_path %>
</div>

app/views/articls/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Articls</h1>

<div id="articls">
  <% @articls.each do |articl| %>
    <%= render articl %>
    <p>
      <%= link_to "Show this articl", articl %>
    </p>
  <% end %>
</div>

<%= link_to "New articl", new_articl_path %>

app/views/articls/new.html.erb
<h1>New articl</h1>

<%= render "form", articl: @articl %>

<br>

<div>
  <%= link_to "Back to articls", articls_path %>
</div>

app/views/articls/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @articl %>

<div>
  <%= link_to "Edit this articl", edit_articl_path(@articl) %> |
  <%= link_to "Back to articls", articls_path %>

  <%= button_to "Destroy this articl", @articl, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>